### PR TITLE
feat: add fabric kotlin project template

### PR DESCRIPTION
**Pull request by zly2006**
Use kotlin in your mod, and kotlin DSL for gradle.

Todo:
- [X] build.gradle.kts
- [ ] Mod.kt & MocClient.kt

### CODE REVIEW

**Comment by Earthcomputer** [comment]
Hi, I'm sure this is a high quality PR and under normal circumstances we'd accept it, but RedNesto is currently in the process of changing how the project creators work, so it might be better to wait for that.

**Comment by RedNesto** [comment]
Hey thanks for the PR.
Unfortunately after my creator rewrite is merged your PR won't be of much use.

I'll look into adding kotlin templates after the new creator is up and running, along with a Fabric split sourcesets probably.

**Comment by zly2006** [comment]
> I'll look into adding kotlin templates after the new creator is up and running, along with a Fabric split sourcesets probably.

Oh that's great! Thanks for your work.

Hope some code here could help you ❤️

**Comment by zly2006** [comment]
@RedNesto Hello should I open a PR to [this repo](https://github.com/minecraft-dev/templates)? If you want to support this template, there need a file template variable in my code: FLK_VERSION for fabric language kotlin's version. If you wish to use the template with source split, please tell me what's the variable.

**Comment by RedNesto** [comment]
Not everything is finalized yet and it isn't properly doable right now, so not much you can do currently. I'll look into it soon.

**Pull request closed without merging**
