### PR TITLE
Relicensing MCDev to LGPL 3.0

### PR DESCRIPTION
**Pull request by DenWav**
The current maintainers of this project have decided we want to move to a better license that protects this project and contributors better, namely in this case LGPL 3.0. This license provides good protections for the project, but won't limit any other plugins which may use our extensions.

The new license will be LGPL 3.0 _only_, disallowing future versions. Considering we have no control over what may or may not be in any future GPL licenses, I am uncomfortable with allowing "any future version".

[I will use Forge's relicensing as a template for how to approach ours.](https://github.com/MinecraftForge/MinecraftForge/issues/2789)

*Note*: this PR does not apply thew new `copyright.txt` file (by running `./gradlew format`) to the project, specifically to keep the diff small and readable. Once approved I will then run the necessary `format` task to apply the change.

### Sample consent message:

> I `github user` listed above as `email address` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

### Trivial Contributions

Some members of this list are authors of what are considered `Trivial Contributions`. These are contributions that are too trivial to be copyrightable.
Mostly this includes changes such as <5 line bug fix, or whitespace changes.
Any person listed here as a Trivial Contribution should respond by `2023-01-31` if they have any objections and their contributions can be removed.

----

## Contributors

|      **Accepted**      | **Commits** | **User**              | **Email Addresses**                                                                    | **Comment**                                                                                                                                                                                                                                                                                                                       |
|:----------------------:|:-----------:|:----------------------|:---------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <ul><li>[x] </ul></li> |    1408     | @DenWav<br/>@DemonWav | `kyle@denwav.dev`<br/>`demonwav@gmail.com`<br/>`DemonWav@users.noreply.github.com`     | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319425841)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |     245     | @RedNesto             | `RedNestoMC@gmail.com`<br/>`rednestomc@gmail.com`                                      | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319732885)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |     132     | @stephan-gh<br/>@Minecrell           | `dev@minecrell.net`<br/>`minecrell@minecrell.net`                                      | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1516681040)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |     73      | @marvin-roesch        | `marvinroesch99@gmail.com`                                                             | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1320022680)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |     71      | @Earthcomputer        | `burtonjae@hotmail.co.uk`                                                              | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1320141663)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |     35      | @kashike              | `kashike@vq.lc`                                                                        | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319448695)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |     27      | @jamierocks           | `dev@jamierocks.uk`<br/>`jamie.mansfield.jm@gmail.com`                                 | Consent given via email.                                                                                                                                                                                                                                                                                                                                   |
| <ul><li>[x] </ul></li> |     11      | @gabizou              | `gabizou@me.com`                                                                       | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1321257261)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      8      | @Mysterious-Dev       | `40738104+Mysterious-Dev@users.noreply.github.com`                                     | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319538383)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      8      | @Redrield             | `purbleguy@gmail.com`                                                                  | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319428912)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |      6      | @thiakil              | `x@xandervictory.id.au`<br/>`xander@thiakil.com`                                       | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319438415)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |      4      | @jamezrin             | `mrjaime1999@gmail.com`                                                                | Trivial Contributions: [1](https://github.com/minecraft-dev/MinecraftDev/commit/dcb3dadf6e173721a09c36a4795717a1daf42548), [2](https://github.com/minecraft-dev/MinecraftDev/commit/4c411690181ff6e120fb5caed201c41ff6cfbff4), [3](https://github.com/minecraft-dev/MinecraftDev/commit/7afae6e9b631ca94d60d905882ecebd2b5e3edd9), [4](https://github.com/minecraft-dev/MinecraftDev/commit/028377826c4dc6901ee6d9f508148f6b63f497ec)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      3      | @NoahvdAa             | `ndvdaa@gmail.com`                                                                     | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319650954)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      3      | @Gegy                 | `gegy1000@gmail.com`                                                                   | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319600033)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      3      | @SizableShrimp        | `sizableshrimp@sizableshrimp.me`<br/>`29855886+SizableShrimp@users.noreply.github.com` | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319429793)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |      3      | @Tom-The-Geek         | `23531706+Geek202@users.noreply.github.com`<br/>`tgbryan39@gmail.com`                  | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1532122778)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      3      | @zachbr               | `zach.brown@destroystokyo.com`<br/>`zach@zachbr.io`                                    | Trivial Contributions: [1](https://github.com/minecraft-dev/MinecraftDev/commit/2f8f7e042aedeb4509657e7e8a7db7647a2ec2b6), [2](https://github.com/minecraft-dev/MinecraftDev/commit/ddb909f26964fdf9a7219474079e643e1ac45e6e), [3](https://github.com/minecraft-dev/MinecraftDev/commit/2bd8025846fb0b3bcc7f6b96ccb341fb2deedcab) |
| <ul><li>[x] </ul></li> |      2      | @Aaron1011            | `aa1ronham@gmail.com`                                                                  | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319441778)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |      2      | @Aikar                | `aikar@aikar.co`                                                                       | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1367102851)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      2      | @JBYoshi              | `JBYoshi@users.noreply.github.com`                                                     | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1367005333)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      2      | @ImMorpheus           | `ImMorpheus@users.noreply.github.com`                                                  | Trivial Contributions: [1](https://github.com/minecraft-dev/MinecraftDev/commit/89a3e08ec39432ad9922983f1fe5ea24b43e1ccb), [2](https://github.com/minecraft-dev/MinecraftDev/commit/8ae0f33c0ab02ccdc9a2d1db93253c18f8fcae2a)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @Scarsz               | `truescarsz@gmail.com`                                                                 | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/cb285bb987878b11d859796fe80f5efc003518c7)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @Zidane               | `zidane@spongepowered.org`                                                             | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1321269237)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @CreepyCre            | `39995304+CreepyCre@users.noreply.github.com`                                          | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/3d0845cf0eacb43b5f4fc16e43268c678322401f)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @DaemonUmbra          | `daemon.umbra@gmail.com`                                                               | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319436787)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |      1      | @finalchild           | `finalchild@ourmc.space`                                                               | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1320028292)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @Trigary              | `trigary0@gmail.com`                                                                   | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1320283682)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @darbyjack            | `admin@glaremasters.me`                                                                | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/1c982d58584f9507f58e15bbfb58ad5eceecf320)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | `<deleted_user>`      | `jackdn.dev@gmail.com`                                                                 | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/b61310a5c966019dfb3643dc33f52f98faa3e5d7)                                                                                                                                                                                                             |
| <ul><li>[x] </ul></li> |      1      | @phase                | `jadonflower@gmail.com`                                                                | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/8a7638aa6e6de54ac9797a8db3b0e637496b3c14)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @jammehcow            | `jspartan250@gmail.com`                                                                | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1320999109)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @ewized               | `ewized@gmail.com`                                                                     | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319427921)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |      1      | @LlamaLad7            | `l3gomindstorms@gmail.com`                                                             | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319738479)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @l-Luna               | `16821808+l-Luna@users.noreply.github.com`                                             | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319714884)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |      1      | @marchermans          | `marc.hermans@ldtteam.com`                                                             | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319653426)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @MrAn0nym             | `63542658+MrAn0nym@users.noreply.github.com`                                           | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319588868)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      |                       | `me@foxie.sh`                                                                          | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/8c92a851432b0bc59539c2a06dd8131b7d468d23)                                                                                                                                                                                                             |
| <ul><li>[x] </ul></li> |      1      | @Prospector           | `6166773+Prospector@users.noreply.github.com`                                          | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319430200)                                                                                                                                                                                                                                        |
| <ul><li>[x] </ul></li> |      1      | @RDIL                 | `me@rdil.rocks`                                                                        | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1321219458)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @CrystalMare          | `admin@heaven-craft.net`                                                               | [N/A - No longer use Maven](https://github.com/minecraft-dev/MinecraftDev/commit/a23a4f431c87b97fd58111ba5c9fbc5eb3dd9a5f)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @TheComputerGeek2     | `Sam1010D@gmail.com`                                                                   | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/bd594c9412adef074fb86e6cb08996497f593335)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @Vinetos              | `Vinetosdev@gmail.com`                                                                 | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1320007670)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @Voleil               | `71479859+Voleil@users.noreply.github.com`                                             |                                                                                                                                                                                                                                                                                                                                   | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/d68fde7047113604c5090ba10a9fc067b6b290eb)
| <ul><li>[x] </ul></li> |      1      | @willies952002        | `admin@domnian.com`                                                                    | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/92105fb7bf38599b577080d9d6bdfe5d3f18e9b5)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @Witherking25         | `witherking@withertech.com`                                                            | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1320471662)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @anatawa12            | `anatawa12@icloud.com`                                                                 | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/0b69005c94361940b78bcd4c40aff6eb1da1eb47)                                                                                                                                                                                                             |
| <ul><li>[x] </ul></li> |      1      | @cpw                  | `cpw+github@weeksfamily.ca`                                                            | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1324069042)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @l1ttleO              | `61277953+l1ttleO@users.noreply.github.com`                                            | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/fe07985f341f7f109f7fb257d7a38ffb73b8c7f3)                                                                                                                                                                                                             |
| <ul><li>[x] </ul></li> |      1      | @modmuss50            | `modmuss50@gmail.com`                                                                  | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1319718057)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @noeppi-noeppi        | `noeppinoeppi@gmail.com`                                                               | [Consent](https://github.com/minecraft-dev/MinecraftDev/pull/1907#issuecomment-1336267765)                                                                                                                                                                                                                                                                                                                                  |
| <ul><li>[x] </ul></li> |      1      | @stygigoth            | `99850233+stygigoth@users.noreply.github.com`                                          | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/050896d7e8066ea46e5c71131d846d3c3c2e35ee)                                                                                                                                                                                                             |
| <ul><li>[x] </ul></li> |      1      | @theminecoder         | `theminecoder@users.noreply.github.com`                                                | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/27afcb6567c7d74e1b099d8e3beed8aec012446a)                                                                                                                                                                                                             |
| <ul><li>[x] </ul></li> |      1      | @xxDark               | `19853368+xxDark@users.noreply.github.com`                                             | [Trivial Contribution](https://github.com/minecraft-dev/MinecraftDev/commit/a6b414e726ead2f28ce8635f641602ae60d9bd3d)                                                                                                                                                                                                             |

### CODE REVIEW

**Comment by DenWav** [comment]
I @DenWav (and @DemonWav) listed above as `kyle@denwav.dev` and `demonwav@gmail.com` and `DemonWav@users.noreply.github.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by ewized** [comment]
I @ewized listed above as `ewized@gmail.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Redrield** [comment]
I @Redrield listed above as purbleguy@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by SizableShrimp** [comment]
I @SizableShrimp listed above as `sizableshrimp@sizableshrimp.me` and `29855886+SizableShrimp@users.noreply.github.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Prospector** [comment]
I, @Prospector, consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by l-Luna** [comment]
same same

**Comment by DenWav** [comment]
@l-Luna I'm assuming `same same` means you consent to the new license, right?

**Comment by DaemonUmbra** [comment]
I @DaemonUmbra listed above as daemon.umbra@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

~~(I was 100% sure I would be labelled as "Trivial Contribution" but whatever)~~
Edit: It happened just as I sent this, lawl

**Comment by thiakil** [comment]
I @thiakil  consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Aaron1011** [comment]
I @Aaron1011 listed above as aa1ronham@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser

**Comment by kashike** [comment]
I @kashike listed above as `kashike@vq.lc` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in `license.txt` and `license.lesser`.

**Comment by Mysterious-Dev** [comment]
I @Mysterious-Dev listed above as 40738104+Mysterious-Dev@users.noreply.github.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser

**Comment by MrAn0nym** [comment]
I @MrAn0nym listed above as 63542658+MrAn0nym@users.noreply.github.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Gegy** [comment]
I @Gegy listed above as gegy1000@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by NoahvdAa** [comment]
I @NoahvdAa listed above as `ndvdaa@gmail.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by marchermans** [comment]
I @marchermans listed above as marc.hermans@ldtteam.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by l-Luna** [comment]
> 
@DenWav yes, I consent to relicensing

**Comment by modmuss50** [comment]
I @modmuss50 listed above as modmuss50@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by RedNesto** [comment]
I @RedNesto listed above as RedNestoMC@gmail.com and rednestomc@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by LlamaLad7** [comment]
I @LlamaLad7 listed above as l3gomindstorms@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Vinetos** [comment]
I,@Vinetos listed above as `Vinetosdev@gmail.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in `license.txt` and `license.lesser.`

**Comment by marvin-roesch** [comment]
I @marvin-roesch listed above as marvinroesch99@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by finalchild** [comment]
I @finalchild listed above as finalchild@ourmc.space consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Earthcomputer** [comment]
I @Earthcomputer listed above as burtonjae@hotmail.co.uk consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Trigary** [comment]
I @Trigary listed above as trigary0@gmail.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by KP2048** [comment]
I @Witherking25 listed above as witherking@withertech.com consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by jupjohn** [comment]
I @jammehcow  listed above as `jspartan250@gmail.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by RDIL** [comment]
I @RDIL listed above as `me@rdil.rocks` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by gabizou** [comment]
I @gabizou listed above as `gabizou@me.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Zidane** [comment]
I @Zidane listed above as zidane@spongepowered.org consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by cpw** [comment]
I, listed above as cpw+github@weeksfamily.ca consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by noeppi-noeppi** [comment]
I @noeppi-noeppi listed above as `noeppinoeppi@gmail.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by JBYoshi** [comment]
I @JBYoshi listed above as `JBYoshi@users.noreply.github.com` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by aikar** [comment]
I @aikar listed above as `aikar@aikar.co` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by stephan-gh** [comment]
I @stephan-gh (previously @Minecrell) listed above as `minecrell@minecrell.net` and `dev@minecrell.net` consent to the relicensing of my contributions to the Minecraft Development for IntelliJ project under the license as stated in license.txt and license.lesser.

**Comment by Tom-The-Geek** [comment]
I @Tom-The-Geek listed above as ***@***.***
and ***@***.*** consent to the relicensing of my contributions to
the Minecraft Development for IntelliJ project under the license as stated
in license.txt and license.lesser.

**Comment by Tom-The-Geek** [comment]
github's broken the formatting, so
I am listed above 23531706 + Geek202 [at] users.noreply.github.comand
tgbryan39 [at] gmail.com

**Comment by DenWav** [comment]
That's everyone! Thanks for all the responses, everyone. I'll rebase this PR and run the licenser to update all the license texts and merge this PR.

**Pull request merged**
