### PR TITLE
Use Gradle 4.10.3 for FG3 projects

### LINKED ISSUE #679: Could not find net.minecraftforge:forge:1.15.2-31.1.1_mapped_stable_60-1.15.
Minecraft Development plugin version: 2019.3-1.3.2
IntelliJ Ultimate version: 2019.3.2
Replicated on 2 windows machines and an arch linux machine

When I create a new project, the project is unable to build and is covered in red errors saying various symbols cannot be resolved. When I go to project structure There is a problem that comes up which says 

> Library Gradle: net.minecraftforge:forge:1.15.2-31.1.1_mapped_stable_60-1.15 has broken classes path:   C:\Users\josh-laptop\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.6015.39\jbr\bin\Could not find net.minecraftforge:forge:1.15.2-31.1.1_mapped_stable_60-1.15. [Fix]

I have navigated to the folder and sure enough net.monecraftforge:forge:1.15.2-31.1.1_mapped_stable_60-1.15. is not in it. I don't know if there's a way to manually download this file.

Things I have tried:
Make a mod for 1.15.2 and 1.14.4
Invalidate caches / restart
Uninstall/reinstall plugin
Uninstall/reinstall IntelliJ
Uninstall/reinstall JDK
Used the following JDKs:
- oracle JDK 8 (windows + linux)
- oracle JDK 11 (windows)
- open JDK 8 (linux)
IntelliJ has all the network permissions it would need.
I have replicated this issue three times, on two windows machines and my linux machine as I have said.

Here is my build.gradle:
```
buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '3.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'

version = modVersion
group = modGroup
archivesBaseName = modBaseName

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    // The mappings can be changed at any time, and must be in the following format.
    // snapshot_YYYYMMDD   Snapshot are built nightly.
    // stable_#            Stables are built at the discretion of the MCP team.
    // Use non-default mappings at your own risk. they may not always work.
    // Simply re-run your setup task after changing the mappings to update your workspace.
    mappings channel: 'stable', version: '60-1.15'
    // makeObfSourceJar = false // an Srg named sources jar is made by default. uncomment this to disable.

    // accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'

            mods {
                testmod {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'

            mods {
                testmod {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'

            args '--mod', 'testmod', '--all', '--output', file('src/generated/resources/')

            mods {
                testmod {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    // Specify the version of Minecraft to use, If this is any group other then 'net.minecraft' it is assumed
    // that the dep is a ForgeGradle 'patcher' dependency. And it's patches will be applied.
    // The userdev artifact is a special name and will get all sorts of transformations applied to it.
    minecraft 'net.minecraftforge:forge:1.15.2-31.1.1'

}
```

I know there was an IntelliJ update recently. From what I've seen online I thought that the plugin and everything should be updated and fine.

I am very familiar with Python & C++, not as much with Java. I have made a simple mod before, but I would not call myself an expert.

### PR DESCRIPTION
**Pull request by RedNesto**
Fixes #679

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
Why 4.10 exactly?

**Comment by RedNesto** [comment]
Because that's the version forge is using right now https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/gradle/wrapper/gradle-wrapper.properties

**Comment by DenWav** [comment]
Of course FG3 would still require a very old version of Gradle...

Can you go ahead and change `FG2_WRAPPER_VERSION` to `FG_WRAPPER_VERSION` in that case too?

**Comment by Niko-sk2x** [comment]
FG3 should work with new gradle versions, up to even 5.6, but not 6.x.

**Comment by RedNesto** [comment]
@DemonWav I ~kinda~ forgot to rename it

> FG3 should work with new gradle versions, up to even 5.6, but not 6.x.

Well, the Gradle version the plugin is using by default is 5.6.1, but it breaks FG3, downgrading to 4.10.3 works, haven't tested version in between. I thought it could work with 5.x too tbh.
Do you have a source claiming 5.x support ?

**Comment by Niko-sk2x** [comment]
Not specifically 5.6, I didn't know of anything breaking around 5.6 (but I didn't try 5.6.1 specifically). But these PRs being merged would imply it to be supported:
https://github.com/MinecraftForge/ForgeGradle/pull/585
https://github.com/MinecraftForge/ForgeGradle/pull/625

**Comment by RedNesto** [comment]
Oh kill me already, I did several dozens of runs with 5.4.1, 5.5.1 and 5.6.1. 5.4.1 seemed to always work, the other two were always failing until _something_ happened and they started working too. Not sure if I cleaned enough of the forge_gradle cache (deleted my build dir too), I always did the same thing.
I doubt these issues are sporadic, I'm starting to go crazy because of this.

Let's stick with 4.10.3 because that's what the latest (1.15.2 - 31.2.8) MDK is using. People can still update Gradle to whatever they want, that's up to them.

**Comment by RedNesto** [comment]
@DemonWav Done

**Pull request merged**
