### PR TITLE
Replaced old Mixin Gutter Icons for "better" ones.

### PR DESCRIPTION
**Pull request by PSJahn**
Simpler and cleaner Mixin gutter Icons, that don't look really weird like the old ones did, following the [IntelliJ design principles](https://jetbrains.design/intellij/principles/icons/)

### CODE REVIEW

**Comment by Earthcomputer** [comment]
Hi, can you please explain why these icons are better, and which of the design principles you believe it follows better than the existing icon? The "weird" icon you are referring to is the Mixin logo.

**Comment by PSJahn** [comment]
Hi there, whilst the larger sized icons for mixins are fine, you can't really tell what the smaller ones are supposed to be depicting, unless you know them.
A lot of people on the Fabric Discord also didn't know what the small icon and gutter icon were supposed to be. The more simplistic "M" approach signals a clear indicator for Mixins, and when it comes to the [design principles](https://jetbrains.design/intellij/principles/icons/) linked above, it mainly refers to [point 4](https://jetbrains.design/intellij/principles/icons/#04), which is visual clutter, [point 7](https://jetbrains.design/intellij/principles/icons/#07), which is using basic shapes and [point 12](https://jetbrains.design/intellij/principles/icons/#12) which refers to blurry icons, as the mixin logo simply downscaled to such a small resolution is very blurred and hard to make out.

**Comment by DenWav** [comment]
The major issue is the M doesn't convey it's Mixin at all, as unless I'm mistaken it's not any kind of official icon for the project. The Mixin icon is literally the logo for the Mixin project, I don't understand how that's confusing.

**Comment by DenWav** [comment]
I'd rather get nicer images for the smaller icons that still use the Mixin logo, if possible.

**Comment by PSJahn** [comment]
> The major issue is the M doesn't convey it's Mixin at all, as unless I'm mistaken it's not any kind of official icon for the project. The Mixin icon is literally the logo for the Mixin project, I don't understand how that's confusing.

Considering that most people haven't encountered the full-scale SpongePowered mixin logo, it's more probable for them to associate the 'M' with 'Mixin', rather than some weird looking pixels.

This issue isn't present with the higher resolution images, where you can more clearly make out what the images are supposed to be depicting, which is why i left them unchanged accordingly.

**Comment by l-Luna** [comment]
the plugin should use standard icons instead of making up its own, which is also what official IntelliJ plugins do.

**Pull request closed without merging**
