### PR TITLE
[Language] Add French

### PR DESCRIPTION
**Pull request by ArnaudLier**

### CODE REVIEW

**Comment by RedNesto** [comment]
The plugin doesn't support localization at the moment (and the only message in the bundle isn't even used)

I have been considering working on it since a few months though. I'll see what needs to be done.

**Comment by DenWav** [comment]
Yeah this is something I've been meaning to work on for a long time, and put some work into internationalizing the code, but there's a lot that still needs to be done. Hopefully we can do that soon and you can contribute a full language pack for us. :)

**Comment by DenWav** [comment]
The biggest challenge is going through the whole code base and finding every string which is human-readable and convert it. Takes a decent amount of grunt work to do that.

**Comment by RedNesto** [comment]
I fixed localization in https://github.com/minecraft-dev/MinecraftDev/commit/929571a40cb4e26666491a057791e93167bf0cc8.
There's an example of how to use the message bundle directly, and how to translate actions.

**Comment by RedNesto** [comment]
Closing this PR for inactivity.

If anyone's interested in localizing the plugin and need help just ask in our discord server.

**Pull request closed without merging**
