### PR TITLE
Another #330 fix attempt

### PR DESCRIPTION
**Pull request by DaemonUmbra**

### CODE REVIEW

**Comment by DenWav** [comment]
Is there a reason you closed this?

**Comment by DaemonUmbra** [comment]
I thought it was stale, also I'm questioning if I could have done it better

**Comment by DenWav** [comment]
I just work on this project in bursts since finding time and motivation is rather difficult for me right now. So unfortunately stuff sits for a while sometimes - right now there seems to be some big issues I need to address so those kind of take priority whenever I do work on this. I'll try and work this PR in next time.

Feel free to update this PR if you have better ideas and when I get around to it, I'll review it and either merge it or give my feedback.

**Comment by DenWav** [comment]
I tested out the current code and I don't think #330 is still an issue. Also, I looked at your code here and don't see really any difference between it and what I had. However, the code did have some room for improvement so I went ahead and committed that and gave credit for the commit to you since I based it on this commit.

2db03de8258cb4ef6c3c84e87bd9cc09eca42c05

**Pull request closed without merging**
