### PR TITLE
Code generation template ideas

### PR DESCRIPTION
**Pull request by Tom-The-Geek**
This pull request adds the idea that I suggested in #775, as well as a few other templates for modders who are starting out.
Currently it contains templates for:
- Forge:
   - Empty block
   - Empty item
   - A simple packet class with an `encoder`, `decoder` and `consumer`
- Fabric:
   - Empty block
   - Empty item

The `New -> MinecraftDev` option is only visible if the module has the Minecraft facet and the available templates are specific based on the modding platform in use.
A GIF of the generation and an image of the new templates section are on a gist [here](https://gist.github.com/Geek202/ac9367997f977a7590b65ffbd01fb6da).

The icon I created for the `Skeleton` section of the templates page is not final and could definitely be a lot better.
Optinions, suggestions and improvements are welcome!

### CODE REVIEW

**Comment by DenWav** [comment]
Overall seems good, I think maybe `New -> Minecraft Class` instead of `New -> MinecraftDev`? I think that might look better.

**Comment by Tom-The-Geek** [comment]
I've updated the action name in the plugin.xml and in the action class, and I agree that `New -> Minecraft Class` looks better.

**Comment by Earthcomputer** [comment]
I definitely like the idea of this, creating new blocks, especially in Fabric, is a little cumbersome with several steps, and it would be nice to be able to make at least simple decorative blocks mostly with templates. It would be nice to generate simple block and item jsons like this as well for Fabric, and data generators for Forge, but those can be left out for now.

**Comment by DenWav** [comment]
You need to run `./gradlew format` and fix any issues it reports that it can't automatically fix.

**Comment by Tom-The-Geek** [comment]
I think I ran that task before pushing the initial code, but I'll re-run the task just to be sure

**Comment by Tom-The-Geek** [comment]
Just checked, and `gradlew format` reported no issues

**Comment by DenWav** [comment]
GitHub actions is bad. I've moved off it because they were failing so much. Sorry about that.

**Pull request merged**
