### PR TITLE
Add option to select official mappings for FabricMC mods

### LINKED ISSUE #1929: Add function to select mapping between yarn and official mapping
### Minecraft Development for IntelliJ plugin version

2022.2-1.5.21

### Description of the feature request

Add function to select mapping between yarn and official mapping

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
All is in the title ^^/.

This close #1929 & #771.

### CODE REVIEW

**Comment by Mysterious-Dev** [comment]
Can we re-run actions with the fix of #1949 ?

**Comment by Earthcomputer** [comment]
I reran them but it's still failing.

**Comment by Mysterious-Dev** [comment]
Yep, I forgot to rebase/merge the branch. It's done.

**Comment by Mysterious-Dev** [comment]
All tests passed ^^. It's good.

**Review by Earthcomputer — APPROVED** [review]
This is good for a temporary solution, although in the future we will change this to something more general for mappings.

**Pull request merged**
