### PR TITLE
Forge only wants lowercased MODIDs, let's sanity check that!

### PR DESCRIPTION
**Pull request by cpw**
In line with vanilla since 1.11, modids should only be lowercase. This PR attempts to (no doubt awfully) try and enforce that restriction for Forge mods.

### CODE REVIEW

**Comment by DenWav** [comment]
In this case perhaps the creator should have separate fields for mod name and mod id, right? Since mod name wouldn't also have this restriction.

**Comment by cpw** [comment]
The mod's name isn't generally the modid no. The modid has some special rules. All lowercase is the biggest one. It gets transformed into a file path which means no colons. It also has a length restriction.

**Comment by stephan-gh** [comment]
The same applies to Sponge so it would be good to have the separate fields for name + ID and the check there as well.

**Comment by DenWav** [comment]
Do you want to try and fiddle with the UI to accomplish that @cpw? Feel free if you do. If not, it won't be difficult for me to implement this.

**Comment by cpw** [comment]
I think you know your way around the UI better than I do @DemonWav.

**Comment by DenWav** [comment]
I've created issue #339 to address this, as I'll be making changes to the UI to fix this.

**Pull request closed without merging**
