### PR TITLE
Resource Filtering

### PR DESCRIPTION
**Pull request by jaime29010**

### CODE REVIEW

**Comment by DemonWav** [comment]
I'm fine with the first commit, but I'm not quite sure about the second. The wording feels more awkward to me, but I'll see if I can get more input on that from others.

**Comment by DemonWav** [comment]
You need to enable filtering with Gradle as well, not just Maven.

**Comment by jaime29010** [comment]
Okay, I'll add filtering with Gradle in the next commit.

**Comment by jaime29010** [comment]
I have tested it and it works, it replaces ${VERSION} with @version@ or ${project.version} respectively on the BuildSystem of the module

**Comment by DemonWav** [comment]
You already have the BuildSystem in the #create() method of ProjectConfiguration, no need to get a new instance in the template util class.

**Comment by jaime29010** [comment]
Couldn't the "When To Load This Plugin" be changed to something else? Like "Loading stage" or something else. Or just "When to load this plugin".

**Pull request merged**
